[package]
name = "orderbook_aggregator_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
log.workspace = true
env_logger.workspace = true
clap.workspace = true
prost = "0.12"
tonic = "0.11"
tokio-stream = "0.1"

[build-dependencies]
tonic-build = "0.11"